//
//  LogsWorker.swift
//  IteoLogger
//
//  Created by Patryk Średziński on 05/02/2021.
//  Copyright (c) 2021 iteo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates by Patryk Średziński
//

import Foundation

protocol FiltersWorker {
    func saveFilters(_ filters: LogFilter) throws
}

final class FiltersWorkerImpl {

    private let userDefaults: UserDefaults
    private let decoder: JSONDecoder
    private let encoder: JSONEncoder

    init(userDefaults: UserDefaults,
         decoder: JSONDecoder,
         encoder: JSONEncoder) {
        self.userDefaults = userDefaults
        self.decoder = decoder
        self.encoder = encoder
    }
    
}

extension FiltersWorkerImpl: FiltersWorker {

    func saveFilters(_ filters: LogFilter) throws {
        let encodedData = try encoder.encode(filters)
        userDefaults.set(encodedData, forKey: LogFilter.userDefaultsKey)
    }

}

private extension FiltersWorkerImpl {
    
}
