//
//  LogsWorker.swift
//  IteoLogger
//
//  Created by Patryk Średziński on 05/02/2021.
//  Copyright (c) 2021 iteo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates by Patryk Średziński
//

import Foundation

protocol FiltersWorker {
    
}

final class FiltersWorkerImpl {
    
    init() {
    }
    
}

extension FiltersWorkerImpl: FiltersWorker {
    
}

private extension FiltersWorkerImpl {
    
}
