//
//  FiltersControllerCreator.swift
//  IteoLogger
//
//  Created by Patryk Średziński on 05/02/2021.
//  Copyright (c) 2021 iteo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates by Patryk Średziński
//

import Foundation

struct FiltersControllerCreator {

    func getController(filter: LogFilter, 
                       availableFrameworks: Set<String>,
                       availableModules: Set<IteoLoggerModule>,
                       availableLevels: Set<IteoLoggerLevel>, 
                       delegate: FiltersRouterDelegate?) -> FiltersController {

        let worker = FiltersWorkerImpl(userDefaults: .standard, decoder: JSONDecoder(), encoder: JSONEncoder())
        let router = FiltersRouterImpl()
        let presenter = FiltersPresenterImpl<FiltersController>()
        let interactor = FiltersInteractorImpl(presenter: presenter, 
                                               worker: worker,
                                               router: router,
                                               filter: filter, 
                                               availableFrameworks: availableFrameworks,
                                               availableModules: availableModules,
                                               availableLevels: availableLevels)
        let viewModel = FiltersViewModel()
        let controller = FiltersController(viewModel: viewModel, interactor: interactor)

        presenter.controller = controller
        router.controller = controller
        router.delegate = delegate

        return controller
        
    }
}
