//
//  LogsRouter.swift
//  IteoLogger
//
//  Created by Patryk Średziński on 05/02/2021.
//  Copyright (c) 2021 iteo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates by Patryk Średziński
//

import UIKit

protocol LogsRouter {
    func displaySharingController(_ logHeader: String, _ logFileUrl: URL)
    func displayFilters(_ filters: LogFilter,
                        availableFrameworks: Set<String>,
                        availableModules: Set<IteoLoggerModule>,
                        availableLevels: Set<IteoLoggerLevel>,
                        delegate: FiltersRouterDelegate?)
}

final class LogsRouterImpl {
    weak var controller: IteoLoggerBaseViewController?
}

extension LogsRouterImpl: LogsRouter {

    func displaySharingController(_ logHeader: String, _ logFileUrl: URL) {
        let activityController = UIActivityViewController(activityItems: [logHeader, logFileUrl], applicationActivities: nil)
        controller?.present(activityController, animated: true, completion: nil)
    }
    
    func displayFilters(_ filters: LogFilter,
                        availableFrameworks: Set<String>,
                        availableModules: Set<IteoLoggerModule>,
                        availableLevels: Set<IteoLoggerLevel>,
                        delegate: FiltersRouterDelegate?) {
        let filterToSend = filters.isSet ? filters : LogFilter(frameworks: .all, levels: .all, modules: .all)
        let filterController = FiltersControllerCreator().getController(filter: filterToSend,
                                                                        availableFrameworks: availableFrameworks,
                                                                        availableModules: availableModules,
                                                                        availableLevels: availableLevels,
                                                                        delegate: delegate)
        controller?.present(filterController, animated: true, completion: nil)
    }
    
}
