//
//  LogsControllerCreator.swift
//  IteoLogger
//
//  Created by Patryk Średziński on 05/02/2021.
//  Copyright (c) 2021 iteo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates by Patryk Średziński
//

import Foundation

struct LogsControllerCreator {

    func getController(logsDirectoryName: String,
                       groupIdentifier: String,
                       shareFormat: String) -> LogsController {

        let dateFormatter = DateFormatManager.shared
        let worker = LogsWorkerImpl(logsDirectoryName: logsDirectoryName,
                                    groupIdentifier: groupIdentifier,
                                    shareFormat: shareFormat)
        let router = LogsRouterImpl()
        let presenter = LogsPresenterImpl<LogsController>()
        let interactor = LogsInteractorImpl(presenter: presenter, worker: worker, router: router)
        let viewModel = LogsViewModel()
        let controller = LogsController(viewModel: viewModel, interactor: interactor, shareFormat: shareFormat, dateFormatter: dateFormatter)

        presenter.controller = controller
        router.controller = controller

        return controller
        
    }
}
